# This is a sample Nginx configuration file for a reverse proxy setup.
# The configuration defines a custom log format named 'upstream_log' that captures various details about client requests and upstream server responses.
log_format upstream_log
    # 客户端的 IP 地址
    '$remote_addr '
    # 客户端请求的完整 URL
    '"$request" '
    # Nginx 最终返回给客户端的状态码
    'status=$status '
    # 真正请求到了哪个后端
    'upstream=$upstream_addr '
    # 后端返回的状态码
    'upstream_status=$upstream_status '
    # 整个请求总耗时
    'request_time=$request_time '
    # 后端处理耗时
    'upstream_time=$upstream_response_time';

server {
    listen 80;

    # 访问日志配置，使用自定义的日志格式
    access_log /var/log/nginx/access.log upstream_log;

    location / {
        proxy_pass http://api:8000;
    }
}
